# Generated by Django 2.1.2 on 2018-12-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinstruction',
            old_name='aboutus',
            new_name='instruction_html',
        ),
    ]
