# Generated by Django 2.1.2 on 2018-12-18 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20181218_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='name',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
