# Generated by Django 2.1.2 on 2019-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromtheTPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_django', models.CharField(help_text='Name on django-admin', max_length=255, unique=True)),
                ('message', models.TextField(help_text='Plaintext message')),
                ('pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/')),
                ('name', models.CharField(help_text='Name of the TPO', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class_name', models.CharField(blank=True, help_text='Icons are provided by Icomoon and can be controlled by a class name.', max_length=255, null=True)),
                ('value', models.PositiveIntegerField(help_text='Provide a value to be displayed.')),
                ('speed', models.PositiveIntegerField(help_text='Speed at which the value increases. Eg. 2000')),
                ('labelname', models.CharField(help_text='Label to be displayed.', max_length=255, unique=True)),
                ('trailing_chars', models.CharField(blank=True, help_text='If you want 90 %add % ', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='slides are sorted based on this.', unique=True)),
                ('overlay_text', models.TextField(help_text='Text on the slide.', unique=True)),
                ('slider_pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/slides/')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maintain a single copy. Edit, do not create additionals.', max_length=255, null=True)),
                ('welcomemessage', models.TextField(help_text='Enter the html content of the welcome message.')),
            ],
        ),
    ]
