# Generated by Django 2.1.2 on 2018-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(help_text='Icons are provided by Icomoon and can be controlled by a class name.', max_length=255, null=True)),
                ('info', models.CharField(help_text='information', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterQuicklink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(help_text='Name of the link: Eg. NITC.', max_length=255, null=True, unique=True)),
                ('url', models.URLField(help_text='Name of the link: Eg. https://nitc.ac.in')),
            ],
        ),
        migrations.CreateModel(
            name='FromtheTPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Plaintext message')),
                ('pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/')),
                ('name', models.CharField(help_text='Name of the TPO', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class_name', models.CharField(blank=True, help_text='Icons are provided by Icomoon and can be controlled by a class name.', max_length=255, null=True)),
                ('value', models.PositiveIntegerField(help_text='Provide a value to be displayed.')),
                ('speed', models.PositiveIntegerField(help_text='Speed at which the value increases. Eg. 2000')),
                ('labelname', models.CharField(help_text='Label to be displayed.', max_length=255, unique=True)),
                ('trailing_chars', models.CharField(blank=True, help_text='If you want 90 %add % ', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='slides are sorted based on this.', unique=True)),
                ('overlay_text', models.TextField(help_text='Text on the slide.', unique=True)),
                ('slider_pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/slides/')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomemessage', models.TextField(help_text='Enter the html content of the welcome message.')),
            ],
        ),
    ]
