# Generated by Django 2.1.2 on 2018-12-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessage',
            name='name',
            field=models.CharField(help_text='Maintain a single copy. Edit, do not create additionals.', max_length=255, null=True),
        ),
    ]
