# Generated by Django 2.1.2 on 2019-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charttype', models.CharField(help_text='Eg. bar ', max_length=255)),
                ('chartlabel', models.CharField(help_text='Eg. Avg Package', max_length=255, unique=True)),
                ('labels', models.TextField(help_text='Enter the labels seperated by commas without spaces after and before comma Eg. (2010,2011,2012) or (cse,ece,eee) or (c s e,e c e,e e e)')),
                ('data', models.TextField(help_text='Enter the data seperated by commas without spaces after and before comma Eg. (110,111,230)')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to be displayed on Django admin. Do not create multiple instances.', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Enter the html content of Policies.')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='static/files/policy/')),
                ('description', models.TextField()),
                ('name', models.CharField(help_text='Name to be displayed on Django admin.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Step number.', unique=True)),
                ('content', models.TextField(help_text='Enter the html content of Step.')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='static/files/statistics/')),
                ('description', models.TextField()),
                ('name', models.CharField(help_text='Name to be displayed on Django admin.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the table. Eg. Place Stats 2018', max_length=255, unique=True)),
                ('content', models.TextField(help_text='HTML content of the table. Make it responsive.')),
                ('number', models.PositiveIntegerField(help_text='Ordering according to this number.')),
            ],
        ),
        migrations.CreateModel(
            name='VisitedCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to be displayed on Django admin. Do not create multiple instances.', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Enter the html content of WhyUs')),
            ],
        ),
    ]
