# Generated by Django 2.1.2 on 2018-12-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the achievement. To be displayed on Django admin.', max_length=255, unique=True)),
                ('pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/achievements/')),
                ('alt_text', models.CharField(help_text='If image does not load, this will be displayed.', max_length=255)),
                ('content', models.TextField(help_text='HTML content of content.')),
                ('date', models.DateField(help_text='Date of the event. Sorted based on this.')),
            ],
        ),
        migrations.CreateModel(
            name='CurLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(help_text='Name of the Branch. Eg. b-CSE for Btech CSE, m-CSE for Mtech', max_length=255, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the achievement. To be displayed on Django admin.', max_length=255, unique=True)),
                ('pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/gallery/')),
                ('alt_text', models.CharField(help_text='If image does not load, this will be displayed.', max_length=255)),
                ('info', models.TextField(help_text='Dexription text of the image.')),
                ('date', models.DateField(help_text='Date of the event. Sorted based on this.')),
            ],
        ),
    ]
