# Generated by Django 2.1.2 on 2018-12-18 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, help_text='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='content',
            field=models.TextField(help_text='Insert content.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='info',
            field=models.TextField(help_text='Description text of the image.'),
        ),
    ]
