# Generated by Django 2.1.2 on 2018-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person.', max_length=255, unique=True)),
                ('info', models.TextField(help_text='html content', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person.', max_length=255, unique=True)),
                ('pic', models.ImageField(default='static/img/slider_3.jpg', upload_to='static/img/people/')),
                ('alt_text', models.CharField(help_text='If image does not load, this will be displayed.', max_length=255)),
                ('phone', models.CharField(help_text='Character field', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('display_in_contactus', models.BooleanField()),
                ('role', models.CharField(choices=[('faculty', 'Faculty'), ('core', 'Core Committee'), ('rep', 'Placement Rep')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReachUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to be displayed on Django admin. Do not create multiple instances.', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Enter the html content of the about us.')),
            ],
        ),
    ]
